# Generated by Django 3.0.4 on 2020-10-16 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateField(default=datetime.datetime.now, verbose_name='опубликовано'),
        ),
    ]
