# Generated by Django 3.0.4 on 2020-11-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='email',
            new_name='client_email',
        ),
    ]
