# Generated by Django 3.1.1 on 2020-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201130_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
