# Generated by Django 3.1.1 on 2020-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201211_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
