# Generated by Django 3.1.1 on 2020-12-11 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20201206_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 6, 8, 32, 442836)),
        ),
    ]
