# Generated by Django 3.1.1 on 2020-12-11 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20201211_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 12, 21, 15, 687047)),
        ),
    ]
