# Generated by Django 3.1.1 on 2020-12-11 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20201211_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 13, 2, 41, 845910)),
        ),
    ]
