# Generated by Django 3.1.1 on 2020-12-11 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20201211_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 13, 3, 27, 720294)),
        ),
    ]
